name: text editor build

on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build-job:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: make
        run: make
